apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: engine-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: engine-service
    spec:
      containers:
      - name: engine-service
        image: iosr/engine-service
        ports:
        - containerPort: 8080
